#!/bin/bash

image_url="https://www.timacad.ru/uploads/media/cache/full_image/uploads/images/20201030/1604034004_ISP_4987.jpg"

num_images=20

original_name_file="classroom_original.jpg"

curl -o "$original_name_file" "$image_url"

for ((i=1; i<=$num_images; i++))
do
    filename="classroom$i.jpg"

    if [ -e "$filename" ]; then
        rm "$filename"
    fi

    cp "$original_name_file" "$filename"
    echo "Смена имени $i картинки"
done

rm $original_name_file

echo "Готово"
